version: "3"

services:
  scraper-api:
    build: ./ATPScraper
    volumes:
      - ./ATPScraper:/usr/src/app
    ports:
      - "5000:80"
    networks:
      - backend
  test-app:
    build: ./test-app
    volumes:
      - "./test-app:/app"
      - "/app/node_modules"
    ports:
      - "3001:3000"
    networks:
      - backend
    environment:
      - NODE_ENV=development
    depends_on:
      - scraper-api

networks:
  backend:
